name: profile_domain
description: Domain layer for the Profile feature
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../../core
  movies_domain:
    path: ../../movies/domain
