name: public_profile_domain
description: Domain layer for the Public Profile feature
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../../core
