name: reviews
description: Reviews UI module for Moovie
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  auto_route: ^11.1.0
  common:
    path: ../common

dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.13.1