name: comments_ui
description: UI module for Comments feature
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  comments:
    path: ../../features/comments
  common:
    path: ../common
  auto_route: ^11.1.0
