name: user_activities
description: User Activities feature module for Moovie
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  user_activities_domain:
    path: domain
  user_activities_data:
    path: data
