name: public_profile_feature
description: Public Profile feature module for Moovie
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  public_profile_domain:
    path: domain
  public_profile_data:
    path: data
