name: comments
description: Comments feature for viewing paginated comments on content
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  comments_domain:
    path: domain
  comments_data:
    path: data
