name: public_profile
description: Public Profile UI module for Moovie
publish_to: none

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  auto_route: ^11.1.0
  common:
    path: ../common
  movies_ui:
    path: ../movies_ui
