name: activities
description: Activities UI module
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  auto_route: any
  common:
    path: ../common
