name: movies_list
description: Movies list UI module for Moovie
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  cached_network_image: any
  infinite_scroll_pagination: any
  auto_route: ^11.1.0
  get_it: ^8.0.3
  common:
    path: ../common
  core:
    path: ../../core
  movies:
    path: ../../features/movies
  movie_detail:
    path: ../movie_detail
  reviews:
    path: ../reviews

dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.13.1
