name: news
edescription: News feature module for Moovie
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  news_domain:
    path: domain
  news_data:
    path: data
