// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/local/local_movie_review_draft.dart';
import 'models/local/local_recent_search.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7225164119965359674),
    name: 'LocalMovieReviewDraft',
    lastPropertyId: const obx_int.IdUid(12, 5320040675716211413),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2815098035594333875),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2737292559545308652),
        name: 'movieId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 7950825517565266487),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8861445596641691518),
        name: 'movieTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 987737510358984256),
        name: 'posterPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9202375440511464123),
        name: 'reviewTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5283946133447879869),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1673376265115291891),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7765618936995239801),
        name: 'isRewatch',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 453665522830252588),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3150717083061644172),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2501738230344671365),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5320040675716211413),
        name: 'reviewBody',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8861921888700839333),
    name: 'LocalRecentSearch',
    lastPropertyId: const obx_int.IdUid(3, 4351401831268948934),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7872867946049279107),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2769940816338134549),
        name: 'query',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7097129463505146758),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4351401831268948934),
        name: 'searchedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8861921888700839333),
    lastIndexId: const obx_int.IdUid(2, 7097129463505146758),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  // ignore: strict_raw_type
  final bindings = <Type, obx_int.EntityDefinition>{
    LocalMovieReviewDraft: obx_int.EntityDefinition<LocalMovieReviewDraft>(
      model: _entities[0],
      toOneRelations: (LocalMovieReviewDraft object) => [],
      toManyRelations: (LocalMovieReviewDraft object) => {},
      getId: (LocalMovieReviewDraft object) => object.id,
      setId: (LocalMovieReviewDraft object, int id) {
        object.id = id;
      },
      objectToFB: (LocalMovieReviewDraft object, fb.Builder fbb) {
        final movieTitleOffset = fbb.writeString(object.movieTitle);
        final posterPathOffset = fbb.writeString(object.posterPath);
        final reviewTitleOffset = fbb.writeString(object.reviewTitle);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        final reviewBodyOffset = fbb.writeString(object.reviewBody);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.movieId);
        fbb.addOffset(2, movieTitleOffset);
        fbb.addOffset(3, posterPathOffset);
        fbb.addOffset(4, reviewTitleOffset);
        fbb.addFloat64(5, object.rating);
        fbb.addBool(6, object.isFavorite);
        fbb.addBool(7, object.isRewatch);
        fbb.addOffset(8, tagsJsonOffset);
        fbb.addInt64(9, object.statusIndex);
        fbb.addInt64(10, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(11, reviewBodyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final movieIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final movieTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final posterPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final reviewTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final reviewBodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final ratingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final isRewatchParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final tagsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = LocalMovieReviewDraft(
          id: idParam,
          movieId: movieIdParam,
          movieTitle: movieTitleParam,
          posterPath: posterPathParam,
          reviewTitle: reviewTitleParam,
          reviewBody: reviewBodyParam,
          rating: ratingParam,
          isFavorite: isFavoriteParam,
          isRewatch: isRewatchParam,
          tagsJson: tagsJsonParam,
          statusIndex: statusIndexParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    LocalRecentSearch: obx_int.EntityDefinition<LocalRecentSearch>(
      model: _entities[1],
      toOneRelations: (LocalRecentSearch object) => [],
      toManyRelations: (LocalRecentSearch object) => {},
      getId: (LocalRecentSearch object) => object.id,
      setId: (LocalRecentSearch object, int id) {
        object.id = id;
      },
      objectToFB: (LocalRecentSearch object, fb.Builder fbb) {
        final queryOffset = fbb.writeString(object.query);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, queryOffset);
        fbb.addInt64(2, object.searchedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final searchedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = LocalRecentSearch(
          id: idParam,
          query: queryParam,
          searchedAt: searchedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalMovieReviewDraft] entity fields to define ObjectBox queries.
class LocalMovieReviewDraft_ {
  /// See [LocalMovieReviewDraft.id].
  static final id = obx.QueryIntegerProperty<LocalMovieReviewDraft>(
    _entities[0].properties[0],
  );

  /// See [LocalMovieReviewDraft.movieId].
  static final movieId = obx.QueryIntegerProperty<LocalMovieReviewDraft>(
    _entities[0].properties[1],
  );

  /// See [LocalMovieReviewDraft.movieTitle].
  static final movieTitle = obx.QueryStringProperty<LocalMovieReviewDraft>(
    _entities[0].properties[2],
  );

  /// See [LocalMovieReviewDraft.posterPath].
  static final posterPath = obx.QueryStringProperty<LocalMovieReviewDraft>(
    _entities[0].properties[3],
  );

  /// See [LocalMovieReviewDraft.reviewTitle].
  static final reviewTitle = obx.QueryStringProperty<LocalMovieReviewDraft>(
    _entities[0].properties[4],
  );

  /// See [LocalMovieReviewDraft.rating].
  static final rating = obx.QueryDoubleProperty<LocalMovieReviewDraft>(
    _entities[0].properties[5],
  );

  /// See [LocalMovieReviewDraft.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<LocalMovieReviewDraft>(
    _entities[0].properties[6],
  );

  /// See [LocalMovieReviewDraft.isRewatch].
  static final isRewatch = obx.QueryBooleanProperty<LocalMovieReviewDraft>(
    _entities[0].properties[7],
  );

  /// See [LocalMovieReviewDraft.tagsJson].
  static final tagsJson = obx.QueryStringProperty<LocalMovieReviewDraft>(
    _entities[0].properties[8],
  );

  /// See [LocalMovieReviewDraft.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<LocalMovieReviewDraft>(
    _entities[0].properties[9],
  );

  /// See [LocalMovieReviewDraft.updatedAt].
  static final updatedAt = obx.QueryDateProperty<LocalMovieReviewDraft>(
    _entities[0].properties[10],
  );

  /// See [LocalMovieReviewDraft.reviewBody].
  static final reviewBody = obx.QueryStringProperty<LocalMovieReviewDraft>(
    _entities[0].properties[11],
  );
}

/// [LocalRecentSearch] entity fields to define ObjectBox queries.
class LocalRecentSearch_ {
  /// See [LocalRecentSearch.id].
  static final id = obx.QueryIntegerProperty<LocalRecentSearch>(
    _entities[1].properties[0],
  );

  /// See [LocalRecentSearch.query].
  static final query = obx.QueryStringProperty<LocalRecentSearch>(
    _entities[1].properties[1],
  );

  /// See [LocalRecentSearch.searchedAt].
  static final searchedAt = obx.QueryDateProperty<LocalRecentSearch>(
    _entities[1].properties[2],
  );
}
