import 'package:flutter/material.dart';

import 'package:common/src/theme/moovie_colors.dart';

abstract final class MoovieColorScheme {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: MoovieColors.primary,
    onPrimary: MoovieColors.neutral,
    primaryContainer: MoovieColors.primaryContainer,
    onPrimaryContainer: MoovieColors.onPrimaryContainer,
    secondary: MoovieColors.secondary,
    onSecondary: MoovieColors.primary,
    secondaryContainer: MoovieColors.secondaryContainer,
    onSecondaryContainer: MoovieColors.onSecondaryContainer,
    tertiary: MoovieColors.tertiary,
    onTertiary: MoovieColors.primary,
    tertiaryContainer: MoovieColors.tertiaryContainer,
    onTertiaryContainer: MoovieColors.onTertiaryContainer,
    error: MoovieColors.error,
    onError: MoovieColors.onError,
    errorContainer: MoovieColors.errorContainer,
    onErrorContainer: MoovieColors.onErrorContainer,
    surface: MoovieColors.surfaceLight,
    onSurface: MoovieColors.onSurfaceLight,
    surfaceContainerHighest: MoovieColors.surfaceVariantLight,
    onSurfaceVariant: MoovieColors.onSurfaceVariantLight,
    outline: MoovieColors.outlineLight,
    outlineVariant: MoovieColors.outlineVariantLight,
    shadow: MoovieColors.shadow,
    scrim: MoovieColors.scrim,
    inverseSurface: MoovieColors.inverseSurfaceLight,
    onInverseSurface: MoovieColors.inverseOnSurfaceLight,
    inversePrimary: MoovieColors.inversePrimaryLight,
    surfaceContainerLow: MoovieColors.surfaceContainerLight,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: MoovieColors.inversePrimaryLight,
    onPrimary: MoovieColors.primaryDark,
    primaryContainer: MoovieColors.primaryLight,
    onPrimaryContainer: MoovieColors.onPrimaryContainer,
    secondary: MoovieColors.secondary,
    onSecondary: MoovieColors.secondaryDark,
    secondaryContainer: MoovieColors.secondaryContainerDark,
    onSecondaryContainer: MoovieColors.onSecondaryContainerDark,
    tertiary: MoovieColors.tertiary,
    onTertiary: MoovieColors.tertiaryDark,
    tertiaryContainer: MoovieColors.tertiaryContainerDark,
    onTertiaryContainer: MoovieColors.onTertiaryContainerDark,
    error: MoovieColors.errorDark,
    onError: MoovieColors.onErrorDark,
    errorContainer: MoovieColors.errorContainerDark,
    onErrorContainer: MoovieColors.onErrorContainerDark,
    surface: MoovieColors.surfaceDark,
    onSurface: MoovieColors.onSurfaceDark,
    surfaceContainerHighest: MoovieColors.surfaceVariantDark,
    onSurfaceVariant: MoovieColors.onSurfaceVariantDark,
    outline: MoovieColors.outlineDark,
    outlineVariant: MoovieColors.outlineVariantDark,
    shadow: MoovieColors.shadow,
    scrim: MoovieColors.scrim,
    inverseSurface: MoovieColors.inverseSurfaceDark,
    onInverseSurface: MoovieColors.inverseOnSurfaceDark,
    inversePrimary: MoovieColors.inversePrimaryDark,
    surfaceContainerLow: MoovieColors.surfaceContainerDark,
  );
}